config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # , :path_prefix => 'profile'
  devise_for :users

  # match '/:id', to: 'users#show', via: 'get'
  # controllers: { registrations: 'users/registrations'}
  resources :users, only: [:show]
  # do
  #   member
  # end
  resources :offers do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index]
  # resources :offers, except: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer, only:[:new, :create]
  before_action :authenticate_user!

  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    @offer = Offer.find(@booking.offer_id)
    @user = current_user
  end

  def new
    # we need @offer in our `simple_form_for`
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    # we need `offer_id` to associate booking with corresponding offer
    @booking.offer = @offer
    @booking.user_id = current_user.id

    if @booking.save
      redirect_to bookings_path
      # notice: 'Saved!'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to offer_path(@booking.offer)
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def booking_params
    params.require(:booking).permit(:comment, :place, :offer_id, :user_id, :booking_start, :booking_end)
  end
end

app/views/bookings/_form.html.erb
<div class="container py-5 d-flex justify-content-between">
    <div class="grid">
      <div class="g-col-3 g-start-2">
        <div class="card-header text-center">
          <h2><%= @offer.title %></h2>
          <%# <%= notice %>
          <% if  @offer.photo.attached? %>
            <%= cl_image_tag @offer.photo.key, height: 150, width: 200, crop: :fill %>
          <%else %>
            <%= image_tag "OIP.jpg", height: 150, width: 200, crop: :fill %>
          <% end %>
          <br>
          <br>
          <p><%= @offer.music_style %></p>
          <p><%= @offer.price.to_i %> € </p>
        </div>
        <br>
          <%# <%= notice %>
        <br>
      </div>
    </div>
    <div class="g-col-4 g-start-6 text-center">
      <%= simple_form_for([@offer, @booking]) do |f| %>
      <%= f.input :booking_start, label: "date de début de la prestation", as: :date, html5: true %>
      <%= f.input :booking_end, label: "date de fin de la prestation", as: :date, html5: true %>
      <%= f.input :place, label: "Lieu de la prestation", placeholder: 'lieu de la prestation' %>
      <%= f.input :comment, label: "Commentaire", placeholder: 'des précisions à apporter ? ' %>
      <div class="d-flex justify-content-center">
        <%= f.button :submit, 'Réserver', class: 'btn-primary' %>
        <% end %>
      </div>
    </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
<h1> Mes Réservations</h1>
  <ul>
    <% @bookings.each do |booking| %>
      <li><%= link_to booking.place, booking_path(booking) %></li>
    <% end %>
  </ul>
  <%# <%= link_to 'Offers', offers_path(@offer) %>
</div>

<%# <div class="container py-5">
<h1>Mes Réservations</h1>
  <div class="d-flex align-items-center justify-content-between mb-3">
    <div class="row">
      <% @bookings.each do |booking| %>
        <%# <div class="co-12 col-sm-6 col-md-4">
            <%# <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= Offer::IMAGES.sample %>
              <%# <%= link_to booking.place, booking_path(booking), class: "text-decoration-none" do %>
              <%# <%= @booking.offer.title %>
              <%# <%= @booking.offer.price %>
              <%# <%= @booking.user.first_name %>
              <%# <%= @booking.user.last_name %>
            <%# </div>
          <% end %>
        <%# </div>
      <% end %>
    <%# </div>
  </div>
</div> %>

app/views/bookings/new.html.erb
<%= render "form",  offer: @offer, booking: @booking %>

app/views/bookings/show.html.erb
<%# <div class="container d-flex">

<div class="container">
<%# <%= notice %>
   <%# <%= @booking.booking_start %>
<%# </div>
<div class="container">
  <%= @offer.title %>
<%# </div>
</div> %>

<div class="container py-5">
  <h1>Mes Réservations</h1>
    <div class="d-flex align-items-center justify-content-between mb-3">
      <div class="row">
          <div class="co-12 col-sm-6 col-md-4">
            <div class="card-category mini-width" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= Offer::IMAGES.sample %>)">
               <%# <%= link_to booking.place, booking_path(booking), class: "text-decoration-none" do %>
               <p><%= @booking.place %></p>
               <p><%= @booking.booking_start %></p>
               <%# <p><%= @booking.user.first_name %>
               <%# <p><%= @booking.user.last_name %>
               <%# <%= @booking.offer.price.to_i %>
               <%# <%= @booking.user.first_name %>
               <%# <%= @booking.user.last_name %>
            </div>
        <%# <% end %>
     </div>
  </div>
</div>