config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # , :path_prefix => 'profile'
  devise_for :users

  # match '/:id', to: 'users#show', via: 'get'
  # controllers: { registrations: 'users/registrations'}
  resources :users, only: [:show]
  # do
  #   member
  # end
  resources :offers do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index]
  # resources :offers, except: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_one :offer
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]
  # set callbacks and authentificator! etc etc
  # before_action :authenticate_user!
  # before_action :set_user, only: [:show]

  def show
    set_user
    @offer = Offer.find_by(user_id: current_user.id)
  end

  # def musician?
  #   current_user.musician == true
  # end
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to edit_offer(@user)
  #     redirect_to offer(current_user)
  #   else
  #     render :new
  #   end
  # end

  # def destroy
  #   @offer.destroy
  #   # redirect_to
  # end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end
  # def set_offer
  #   @offer = Offer.find(params[:id])
  # end

  def user_params
    params.require(:user).permit(:musician)
  end
end

app/views/users/profile.html.erb
 <h1><div class="container">profile page</h1>
  <%# <%= render "form", restaurant: @restaurant %>
  <%# <%= render 'offers/show.html.erb' %>
  <h1 class="container">My offers</h1>
  <%= render template: "offers/index" %>
  <%= @user.email %>
  <%= link_to "Profile", current_user %>
</div>
<h2>profile </h2>
<% @users.each do |user| %>
<%= user.email  %>
<% end %>
<%# <p id="notice"><%= notice %>

<h1>user show page</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.name %>
</p>

<!-- include others, etc. -->

<%= link_to 'Edit Profile', edit_user_path(@user) %> |


<%#= link_to "Settings", edit_user_path %>

app/views/users/show.html.erb
<div class = "container">
  <h2><%= @user.username %></h2>
  <ul class="user-group">
      <li class="list-group-item"><%= @user.first_name %></li>
      <li class="list-group-item"><%= @user.last_name %></li>
      <li class="list-group-item"><%= @user.email %></li>
  </ul>
  <div class = "d-flex justify-content-center">
      <div class="text-center">
        <% if current_user.musician == true %>
        <%= link_to 'Créer ma fiche produit', new_offer_path(), class: "btn"%>
        <%= link_to 'Mettre à jour ma fiche produit', edit_offer_path(), class: "btn"%>
        <div class = "card">
          <h5>Votre offre à ce jour :</h5>
           <% if current_user.offer != nil %>
            <h2><%= @offer.title %></h2>
              <%= render 'offers/card', offer: @offer %>
          <% end %>
        <% else %>
        <%= link_to 'Mes réservations', bookings_path(), class: "btn"%>
        <% end %>
     </div>

        </div>
    </div>
</div>