config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # , :path_prefix => 'profile'
  devise_for :users

  # match '/:id', to: 'users#show', via: 'get'
  # controllers: { registrations: 'users/registrations'}
  resources :users, only: [:show]
  # do
  #   member
  # end
  resources :offers do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index]
  # resources :offers, except: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  EVENTS = ["Anniversaire", "Fêtes Religieuses", "Bar/Restaurant/Hôtel", "Concert privé à domicile", "Festival", "Gala","Garden party", "Inauguration", "Mariage/Vin d'honneur/Cérémonie", "Soirée d'entreprise", "Autre"]
  STYLE = ["Bossa Nova/Latino","Chanson française", "Chorales/Gospel", "Classique", "Ensembles à cordes", "Funk/Soul/Disco", "Gipsy/Flamenco", "Guitaristes", "Hard rock/Metal", "Jazz/Jazz Manouche/Blues", "Mariachi", "Orchestres", "Pianistes","Pop/Rock", "Rap/Hip Hop", "Reggae", "Spectacles enfants", "Traditionnelle/Folk"]
  # validates :event, inclusion: { in: EVENTS }
  validates :music_style, inclusion: { in: STYLE }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_music,
    against: [ :title, :music_style ],
    using: {
      tsearch: { prefix: true }
  }

  IMAGES = ["https://res.cloudinary.com/mavana/image/upload/v1648647740/gig/the-last-waltz-concert-the-band-01_d3rfhr.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647722/gig/people-music-band-acoustic-guitar-keyboard-drums-isolated-white-background-189949646_aoslqs.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647706/gig/joan-jett-runaways_pi5znw.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647692/gig/c4d84dee8452cdacaf2ae8d0ed79c21f24-20-roxy-music.rsocial.w1200_bd7ddd.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647682/gig/100-best-rock-bands-of-the-2010s_p6sosb.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647677/gig/5bb26c6d9fb84c06520f607b_uvdw1k.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647673/gig/6d043f817df5b96f2849fa562bfdb202-1200-80_i5qv31.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647670/gig/diverse-young-band-playing-a-song-together-in-a-home-music-studio-picture-id1355093071_ulf8up.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647669/gig/photo-1499364615650-ec38552f4f34_qukyze.jpg",
     "https://res.cloudinary.com/mavana/image/upload/v1648647668/gig/1200px-Mary_Timony_Plays_Helium_with_Hospitality_pbqkvw.jpg"
  ]
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show]

  def index
    if params[:query].present?
      @offers = Offer.search_by_title_and_music(params[:query])
    else
      @offers = Offer.all
    end
    params[:query] = ""
  end

  def new
    @offer = Offer.new
    @user = current_user
  end

  def show
    set_offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :availability_start, :availability_end, :price, :description, :music_style, :photo)
  end
end

app/views/offers/_card.html.erb
<div class="card-header p-3 mb-2 bg-dark text-white row" >

      <%= notice %>
      <div class= "place col-lg-6  col-12">

          <% if  offer.photo.attached? %>
          <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill, class: 'center-img' %>
          <%else %>
          <%= image_tag "OIP.jpg", height: 300, width: 400, crop: :fill, class: 'center-img' 'card-img-top' %>
          <% end %>
      </div>
        <div class= "place col-lg-6  col-12">
          <h2 class= "mb-3"><%= offer.title  %></h2>
          <h3 class= "mb-3">Style de Musique : <%= offer.music_style  %></h3>
          <p class= "mb-3">Qui sommes-nous ? <%= offer.description %></p>
          <p class= "mb-3"><%= offer.availability_start %></p>
          <p class= "mb-3"><%= offer.availability_end %></p>
          <h4><%= offer.price.to_i  %> € </h4>
        </div>
      </div>
</div>

app/views/offers/_form.html.erb
<div class="container">
  <br>
  <%# <%= notice %>
  <br>
  <%= simple_form_for(offer) do |f| %>
    <%= f.input :title %>
    <%= f.submit %>
  <% end %>
</div>

app/views/offers/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/offers/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= Offer::IMAGES.sample %>)">
  <div class="text-center text-white">
    <h1>De super groupes de musique à booker</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<%= form_tag offers_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Band"
  %>
  <div class="btn-center">
    <%= submit_tag "Search", class: "btn btn-primary" %>
  </div>
<% end %>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <div class="row">
      <% @offers.each do |offer| %>
        <div class="co-12 col-sm-6 col-md-4 mini-width">
          <%= link_to offer_path(offer), class: "text-decoration-none" do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= Offer::IMAGES.sample %>)">

              <%= offer.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# (<% Offer::IMAGES.sample%>

app/views/offers/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Création de la fiche du Groupe</h3>
        <%= simple_form_for [@offer] do |f| %>
          <%= f.input :title, label: "Nom du Groupe", placeholder: 'Nom du Groupe' %>
          <%= f.input :description, label: "Description", placeholder: 'Description de la prestation' %>
          <%= f.input :availability_start,  as: :date, html5: true, label: "Nos disponibilités" %>
          <%= f.input :availability_end, as: :date, html5: true %>
          <%= f.input :price, label: "Prix de la prestation", placeholder: 'Prix' %>
          <%# <%= f.input :place, placeholder: 'the place' %>
          <%= f.input :music_style, label: "Votre style de Musique", collection: Offer::STYLE %>
          <%= f.input :photo, as: :file, label: "Photo de votre Groupe" %>
          <%= f.submit "Créer la fiche", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class = "container">
  <p>Vous avez crée 1 offre : </p>

<div class="place-md">
      <%= notice %>

  <div class="card text-center">
    <div class="card-header p-3 mb-2 bg-dark text-white row" >
      <div class= "place col-lg-6  col-12">
        <% if  @offer.photo.attached? %>
        <%= cl_image_tag @offer.photo.key, height: 300, width: 400, crop: :fill, class: 'center-img' %>
        <%else %>
        <%= image_tag Offer::IMAGES.sample, height: 300, width: 400, crop: :fill, class: 'center-img' 'card-img-top' %>
        <% end %>
      </div>
        <div class= "place col-lg-6  col-12">
          <h2 class= "mb-3"><%= @offer.title  %></h2>
          <h3 class= "mb-3">Style de Musique : <%= @offer.music_style  %></h3>
          <p class= "mb-3">Qui sommes-nous ? <%= @offer.description %></p>
          <p class= "mb-3"><%= @offer.availability_start %></p>
          <p class= "mb-3"><%= @offer.availability_end %></p>
          <h4><%= @offer.price.to_i  %> € </h4>
        </div>
      </div>
      <div class="justify-content-between ">
        <%= link_to new_offer_booking_path(@offer), class: 'no-text-decoration' do%>
          <div class='btn-yours no-text-decoration'>Réserver ce groupe</div>
        <% end %>
        <%= link_to root_path, class: 'no-text-decoration' do%>
          <div class='btn-yours no-text-decoration'>Accueil</div>
        <% end %>
        <%= link_to offers_path, class: 'no-text-decoration' do%>
          <div class='btn-yours no-text-decoration'>Un autre groupe ? </div>
      <% end %>
    </div>
    <%# <%= link_to 'Create an offer', new_offer_path(), class: "btn btn-primary" %>
  </div>
</div>
</div>
</div>